-- MySQL Script generated by MySQL Workbench
-- Mon 20 Aug 2018 11:09:35 AM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema training_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema training_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `training_web` DEFAULT CHARACTER SET utf8 ;
USE `training_web`;

-- -----------------------------------------------------
-- Table `training_web`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `training_web`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password_hash` VARCHAR(32) NOT NULL,
  `phone_number` VARCHAR(10) NULL,
  `job_title` VARCHAR(100) NULL,
  `creation_date` DATE NOT NULL,
  `last_login_date` DATE NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `training_web`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `training_web`;
INSERT INTO `training_web`.`users` (`first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `job_title`, `creation_date`, `last_login_date`, `enabled`) VALUES ('Robin', 'Jackman', 'robin_jackman@mysite.com', '2150dcfdb617196949b99cf513c00854', '0730261711', 'Software Engineer', '2010-11-10', '2018-01-09', 1);
INSERT INTO `training_web`.`users` (`first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `job_title`, `creation_date`, `last_login_date`, `enabled`) VALUES ('Taylor', 'Edward', 'taylor_edward@mysite.com', '8f50f8090c5ed33c2934a61bd77ea3a7', '0738144569', 'Software Architect', '2011-09-12', '2018-03-19', 1);
INSERT INTO `training_web`.`users` (`first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `job_title`, `creation_date`, `last_login_date`, `enabled`) VALUES ('Vivian', 'Dickens', 'vivian_dickens@mysite.com', 'b0001a209b4a42cddf240a5ab6010499', '0742656614', 'Database Administrator', '2012-05-14', '2018-03-26', 1);
INSERT INTO `training_web`.`users` (`first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `job_title`, `creation_date`, `last_login_date`, `enabled`) VALUES ('Harry', 'Clifford', 'harry_clifford@mysite.com', 'feb5636a7a647584cbfa40146b3407c4', '0745615088', 'Database Administrator', '2013-12-25', '2018-03-31', 0);
INSERT INTO `training_web`.`users` (`first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `job_title`, `creation_date`, `last_login_date`, `enabled`) VALUES ('Eliza', 'Clifford', 'eliza_clifford@mysite.com', 'e48fd3173f67d2d54333442bdcc96e98', '0761821311', 'Software Engineer', '2013-12-26', '2018-05-09', 1);
INSERT INTO `training_web`.`users` (`first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `job_title`, `creation_date`, `last_login_date`, `enabled`) VALUES ('Nancy', 'Newman', 'nancy_newman@mysite.com', 'a7f783ec8d2aecd437f96da71f56e6f6', '0767127778', 'Software Engineer', '2014-12-02', '2018-06-03', 0);
INSERT INTO `training_web`.`users` (`first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `job_title`, `creation_date`, `last_login_date`, `enabled`) VALUES ('Melinda', 'Clifford', 'melinda_clifford@mysite.com', '3c352a578b66e1913488bcec007e9fbe', '0767638360', 'Project Manager', '2017-06-18', '2018-07-16', 1);
INSERT INTO `training_web`.`users` (`first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `job_title`, `creation_date`, `last_login_date`, `enabled`) VALUES ('Harley', 'Gilbert', 'harley_gilbert@mysite.com', 'c9be6f56735deebc72fada23a4e522bd', '0769622409', 'Software Architect', '2018-05-29', '2018-08-16', 1);
INSERT INTO `training_web`.`users` (`first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `job_title`, `creation_date`, `last_login_date`, `enabled`) VALUES ('First', 'Last', 'test@test.com', '48f4ae40205de798715d2c7214a95810', '0746839519', 'Troll User', '2018-08-20', '2018-08-20', 1);

COMMIT;
